# Chapter-6 Arrays

This notebook contains the sample source code explained in the book *Hands-On Julia Programming, Sambit Kumar Dash, 2021, bpb Publications. All Rights Reserved*.

In [1]:
using Pkg
pkg"activate ."
pkg"instantiate"

  Activating environment at `~/work/books/HOJP/Chapter-06/Project.toml`


## 6.1 Introduction

Arrays are used extensively as they are simple and have a memory layout that can store objects on contiguous addresses. Most importantly they can be used by other datastructure implementations. 

### Container

In [2]:
a = []

Any[]

In [3]:
push!(a, 5)

1-element Vector{Any}:
 5

In [4]:
push!(a, 5, 6, 7, 8)

5-element Vector{Any}:
 5
 5
 6
 7
 8

In [5]:
pop!(a)

8

In [6]:
length(a)

4

In [7]:
isempty(a)

false

In [8]:
empty!(a)

Any[]

In [9]:
isempty(a)

true

In [10]:
push!(a, 1, 2, 3, 4, 5)

5-element Vector{Any}:
 1
 2
 3
 4
 5

In [11]:
popfirst!(a)

1

In [12]:
a

4-element Vector{Any}:
 2
 3
 4
 5

In [13]:
pushfirst!(a, 1)

5-element Vector{Any}:
 1
 2
 3
 4
 5

## 6.2 Dimensions

Arrays are allocated as a linear chunk of memory. They can further reshaped for indexing and access in anyways desirable while keeping the original row major ordering intact.

![image](cube.png)

In [14]:
a = reshape(collect(1:24), 4, 3, 2)

4×3×2 Array{Int64, 3}:
[:, :, 1] =
 1  5   9
 2  6  10
 3  7  11
 4  8  12

[:, :, 2] =
 13  17  21
 14  18  22
 15  19  23
 16  20  24

In [15]:
ndims(a)

3

In [16]:
size(a)

(4, 3, 2)

In [17]:
size(a, 3)

2

## 6.3 Indexing

Considered as the primary means of accessing one or more elements of an array. Variety of indexing schemes exist for arrays beyond simple integer scalars. 

### Scalars

In [18]:
a = reshape(collect(1:24), 4, 3, 2, 1)

4×3×2×1 Array{Int64, 4}:
[:, :, 1, 1] =
 1  5   9
 2  6  10
 3  7  11
 4  8  12

[:, :, 2, 1] =
 13  17  21
 14  18  22
 15  19  23
 16  20  24

In [19]:
a[1, 2, 1, 1]

5

### Ranges

In [20]:
a[:, 1, 1, 1]

4-element Vector{Int64}:
 1
 2
 3
 4

In [21]:
a[2:3, 1, 1, 1]

2-element Vector{Int64}:
 2
 3

In [22]:
a[1:2:3, 1, 1, 1]

2-element Vector{Int64}:
 1
 3

In [23]:
a[1:2:3, 1:2:3, 1, 1]

2×2 Matrix{Int64}:
 1   9
 3  11

### Vectors 

In [24]:
a[1:2:3, 1:2:3, [1], [1]]

2×2×1×1 Array{Int64, 4}:
[:, :, 1, 1] =
 1   9
 3  11

In [25]:
a[1:2:3, [1; 3], 1, 1]

2×2 Matrix{Int64}:
 1   9
 3  11

In [26]:
a[1:2:3, [1, 3], 1, 1]

2×2 Matrix{Int64}:
 1   9
 3  11

In [27]:
b = a[1:2:3, [1 3], 1, 1]

2×1×2 Array{Int64, 3}:
[:, :, 1] =
 1
 3

[:, :, 2] =
  9
 11

In [28]:
a[:, [2], [1], [1]]

4×1×1×1 Array{Int64, 4}:
[:, :, 1, 1] =
 5
 6
 7
 8

In [29]:
a[[1 2; 3 4], [2], [1], [1]]

2×2×1×1×1 Array{Int64, 5}:
[:, :, 1, 1, 1] =
 5  6
 7  8

### Linear Index

Accessing the array as a single element linear index as if the array is flattened to a single dimension vector. 

In [30]:
a = reshape(collect(1:6), (2, 3))

2×3 Matrix{Int64}:
 1  3  5
 2  4  6

In [31]:
a[5]

5

In [32]:
a[1, 3]

5

In [33]:
LinearIndices(a)

2×3 LinearIndices{2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}:
 1  3  5
 2  4  6

### Cartesian Index

Providing indices in each dimension.

In [34]:
A = reshape(collect(1:6), 3, 2)

3×2 Matrix{Int64}:
 1  4
 2  5
 3  6

In [35]:
ci = CartesianIndices(A)

3×2 CartesianIndices{2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}:
 CartesianIndex(1, 1)  CartesianIndex(1, 2)
 CartesianIndex(2, 1)  CartesianIndex(2, 2)
 CartesianIndex(3, 1)  CartesianIndex(3, 2)

### Boolean Index

In [36]:
x = reshape(collect(1:16), 4, 4)

4×4 Matrix{Int64}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

In [37]:
filter = map(ispow2, x)

4×4 Matrix{Bool}:
 1  0  0  0
 1  0  0  0
 0  0  0  0
 1  1  0  1

In [38]:
x[filter]

5-element Vector{Int64}:
  1
  2
  4
  8
 16

In [39]:
x[[false, true, true, false], :]

2×4 Matrix{Int64}:
 2  6  10  14
 3  7  11  15

### Assignment 

In [40]:
a = reshape(collect(1:24), 4, 3, 2, 1)
a[:, 2, 1, 1] = fill(25, 4)

4-element Vector{Int64}:
 25
 25
 25
 25

In [41]:
a

4×3×2×1 Array{Int64, 4}:
[:, :, 1, 1] =
 1  25   9
 2  25  10
 3  25  11
 4  25  12

[:, :, 2, 1] =
 13  17  21
 14  18  22
 15  19  23
 16  20  24

### Special Indices

`begin` and `end` keywords can be used as indices.  

In [42]:
a = reshape(collect(1:24), 4, 3, 2, 1)
a[:, begin, 2, 1], a[:, begin+1, 2, 1]

([13, 14, 15, 16], [17, 18, 19, 20])

In [43]:
a[end, :, 2, 1], a[end-1, :, 2, 1]

([16, 20, 24], [15, 19, 23])

### Interface

The array indices may not start from 1 and end at the highest value. `firstindex` and `lastindex` help find the valid index range. 

In [44]:
firstindex(a)

1

In [45]:
lastindex(a)

24

In [46]:
lastindex(a, 1)

4

In [47]:
lastindex(a, 2)

3

In [48]:
lastindex(a, 3)

2

In [49]:
lastindex(a, 4)

1

## 6.4 Slicing

Accessing a portion of an array as an a standalone array. Normally, slicing operations allocate new arrays. 

In [50]:
a = reshape(collect(1:9), 3, 3)

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [51]:
a[:, 1]

3-element Vector{Int64}:
 1
 2
 3

In [52]:
a[1, :]

3-element Vector{Int64}:
 1
 4
 7

In [53]:
a[1, 2:3]

2-element Vector{Int64}:
 4
 7

In [54]:
b = a[1:2, :]

2×3 Matrix{Int64}:
 1  4  7
 2  5  8

In [55]:
b[1, 2] = 10

10

In [56]:
b

2×3 Matrix{Int64}:
 1  10  7
 2   5  8

In [57]:
a

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [58]:
v = @view a[1:2, :]

2×3 view(::Matrix{Int64}, 1:2, :) with eltype Int64:
 1  4  7
 2  5  8

In [59]:
v[1, 2] = 10

10

In [60]:
v

2×3 view(::Matrix{Int64}, 1:2, :) with eltype Int64:
 1  10  7
 2   5  8

In [61]:
a

3×3 Matrix{Int64}:
 1  10  7
 2   5  8
 3   6  9

## Broadcasting

Ability to reflect one array or collection over the other element wise (can be row or column wise as well) while applying an operation on them.  

In [62]:
a = reshape(collect(1:9), 3, 3)

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [63]:
b = reshape(collect(9:-1:1), 3, 3)

3×3 Matrix{Int64}:
 9  6  3
 8  5  2
 7  4  1

In [64]:
a + b

3×3 Matrix{Int64}:
 10  10  10
 10  10  10
 10  10  10

In [65]:
broadcast(*, a, b)

3×3 Matrix{Int64}:
  9  24  21
 16  25  16
 21  24   9

In [66]:
a .* b

3×3 Matrix{Int64}:
  9  24  21
 16  25  16
 21  24   9

In [67]:
a = reshape(collect(1:9), 3, 3)

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [68]:
b = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [69]:
a .+ b

3×3 Matrix{Int64}:
 2  6  10
 3  7  11
 4  8  12

In [70]:
b = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [71]:
a .+ b

3×3 Matrix{Int64}:
 2  5   8
 4  7  10
 6  9  12

In [72]:
broadcast(string, ("one","two","three","four"), ": ", 1:4)

4-element Vector{String}:
 "one: 1"
 "two: 2"
 "three: 3"
 "four: 4"

In [73]:
string.(("one","two","three","four"), ": ", 1:4)

4-element Vector{String}:
 "one: 1"
 "two: 2"
 "three: 3"
 "four: 4"

### Performance

Does not store intermediate values so can be lesser allocations and better performing. `repeat` takes a block of an array and duplicates it in each dimension.  

In [74]:
v = [1, 2]

2-element Vector{Int64}:
 1
 2

In [75]:
repeat(v, 2, 3) #Repeats twice in dim 1 and thrice in dim 2. 

4×3 Matrix{Int64}:
 1  1  1
 2  2  2
 1  1  1
 2  2  2

Now, simulating the broadcast in the previous example with repeat. 

In [76]:
a + repeat(b, 1, 3)

3×3 Matrix{Int64}:
 2  5   8
 4  7  10
 6  9  12

### broadcast vs. map

broadcast will take care of dimension dissimilarities gracefully by repeating. However, `map` will stop at the lower dimension. 

In [77]:
a

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [78]:
b

3-element Vector{Int64}:
 1
 2
 3

In [79]:
map(+, a, b)

3-element Vector{Int64}:
 2
 4
 6

## 6.6 Reduction

Providing summary of array elements in one or more dimensions. Similar to group by clauses of databases. 

In [80]:
a = reshape(collect(1:16), (2, 2, 2, 2))

2×2×2×2 Array{Int64, 4}:
[:, :, 1, 1] =
 1  3
 2  4

[:, :, 2, 1] =
 5  7
 6  8

[:, :, 1, 2] =
  9  11
 10  12

[:, :, 2, 2] =
 13  15
 14  16

In [81]:
reduce(+, a)

136

### Associativity

Operator precedence can play a significant role on the results obtained by the reduce operation. 

In [82]:
foldl(=>, [1, 2, 3, 4])

((1 => 2) => 3) => 4

In [83]:
foldr(=>, [1, 2, 3, 4])

1 => (2 => (3 => 4))

In [84]:
reduce(=>, [1, 2, 3, 4])

((1 => 2) => 3) => 4

In [85]:
foldl(-, [1, 2, 3, 4])

-8

In [86]:
foldr(-, [1, 2, 3, 4])

-2

In [87]:
reduce(-, [1, 2, 3, 4])

-8

### Map and reduce

`map` and `reduce` method in one function call. 

In [88]:
mapreduce(x->x*x, +, [1, 2, 3, 4])

30

### Slices

map and reduce operation on slice of an array. 

In [89]:
a = reshape(collect(1:16), 2, 2, 2, 2)
mapslices(sum, a, dims=[1, 2])

1×1×2×2 Array{Int64, 4}:
[:, :, 1, 1] =
 10

[:, :, 2, 1] =
 26

[:, :, 1, 2] =
 42

[:, :, 2, 2] =
 58

## 6.7 Abstract Array Types

Abstract arrays provide the array like access interfaces for derived classes to implement. `Array` concrete type also governs the internal storage of elements. One can implement an array type of her own, that is efficient on storage, yet behaves like an array. `MyIdentity` is an identity matrix implemented with only size of matrix information. 1s and 0s are not stored. 

In [90]:
struct MyIdentity{T} <: AbstractMatrix{T}
    l::Int
end

Base.size(m::MyIdentity)=(m.l, m.l)
Base.size(m::MyIdentity, d)=(d == 1 || d == 2) ? m.l : error("Invalid dimensions")

function Base.getindex(m::MyIdentity{T}, i, j) where {T}
    1 <= i <= m.l && 1 <= j <= m.l || error("Invalid indices")
    i == j && return one(T)
    return zero(T)
end

In [91]:
a = MyIdentity{Int}(3)

3×3 MyIdentity{Int64}:
 1  0  0
 0  1  0
 0  0  1

In [92]:
a[1, 2]

0

In [93]:
a = MyIdentity{Float32}(3)

3×3 MyIdentity{Float32}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [94]:
size(a)

(3, 3)

In [95]:
size(a, 1)

3

In [96]:
length(a)

9

In [97]:
similar(a)

3×3 Matrix{Float32}:
 1.1f-44   0.0          1.3f-44
 0.0      -1.00477f-26  0.0
 4.0f-45   4.5656f-41   4.0f-45

In [98]:
IndexStyle(typeof(a))

IndexCartesian()

In [99]:
a[5] # Linear Indexing

1.0f0

In [100]:
a*[1,2,3]

3-element Vector{Float32}:
 1.0
 2.0
 3.0

## 6.8 Sparse Arrays

### Sparse Vector Storage

```
# This is the internal definition of SparseVector in Julia
# It's stated here for refernce only. DO NOT RUN this code. 

struct SparseVector{Tv,Ti<:Integer} <: AbstractSparseVector{Tv,Ti}
    n::Int              # Length of the sparse vector
    nzind::Vector{Ti}   # Indices of stored values
    nzval::Vector{Tv}   # Stored values, typically nonzeros
end
```

In [101]:
using SparseArrays
I = [1, 4, 3, 5]
V = [1, 2, -5, 3]
R = sparsevec(I,V)

5-element SparseVector{Int64, Int64} with 4 stored entries:
  [1]  =  1
  [3]  =  -5
  [4]  =  2
  [5]  =  3

In [102]:
findnz(R)

([1, 3, 4, 5], [1, -5, 2, 3])

### Sparse Matrix Storage

```
# This is the internal definition of SparseMatrixCSC in Julia
# It's stated here for refernce only. DO NOT RUN this code.

struct SparseMatrixCSC{Tv,Ti<:Integer} <: AbstractSparseMatrix{Tv,Ti}
    m::Int                  # Number of rows
    n::Int                  # Number of columns
    colptr::Vector{Ti}      # Column j is in 
                            #      colptr[j]:(colptr[j+1]-1)
    rowval::Vector{Ti}      # Row indices of stored values
    nzval::Vector{Tv}       # Stored values, typically nonzeros
end
```

In [103]:
I = [1, 4, 3, 5]
J = [4, 7, 18, 9]
V = [1, 2, -5, 3]

S = sparse(I, J, V)

5×18 SparseMatrixCSC{Int64, Int64} with 4 stored entries:
⠀⠈⠀⡀⠀⠀⠀⠀⠠
⠀⠀⠀⠀⠁⠀⠀⠀⠀

In [104]:
findnz(S)

([1, 4, 5, 3], [4, 7, 9, 18], [1, 2, 3, -5])

In [105]:
S[1, 2]

0

In [106]:
size(S)

(5, 18)

### Efficiency

Sparce vector and matrice are storage efficient but access may be slower than the dense implementations. So one may need to implement specialized vectors or matrices for some of their usage. 

## 6.9 Linear Algebra

## Exercises