# Chapter-5 Collections


In [1]:
using Pkg
pkg"activate ."
pkg"instantiate"

  Activating environment at `C:\Users\shalo\Desktop\Julia -Sambit\Project.toml`


## 5.1 Predefined Data Structures

Julia language has defined a few standard data structures like

- Arrays
- Tuples
- Dicts
- Sets

## 5.2 Tuple

Immutable data type with a number of comma separated values. We have seen tuples as arguments to functions. Here we shall explore the collection like behavior of a tuples.

In [2]:
a = (1, "string", 1.0)


(1, "string", 1.0)

In [3]:
# Heterogeneous 
typeof(a)                         

Tuple{Int64, String, Float64}

In [4]:
# Accessed as Index
a[1]                              

1

In [5]:
# Immutable
a[1] = 6                          

LoadError: MethodError: no method matching setindex!(::Tuple{Int64, String, Float64}, ::Int64, ::Int64)

In [6]:
# Pattern Matching
b, c = a                        
(1, "string", 1.0)

(1, "string", 1.0)

In [7]:
b

1

In [8]:
c

"string"

### NTuple

N elements of a specific type in a tuple like collection.

In [9]:
NTuple{3, Int}

Tuple{Int64, Int64, Int64}

In [10]:
a = ntuple(x->4, 10)

(4, 4, 4, 4, 4, 4, 4, 4, 4, 4)

In [11]:
typeof(a)

NTuple{10, Int64}

In [12]:
a = ntuple(i->i*1.0, 10)

(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0)

In [13]:
typeof(a)

NTuple{10, Float64}


### Tuple as a Collection

A `Tuple` has collection like properties like it has length method. Can be iterated over. 

In [14]:
length(a)

10

In [15]:
for i=1:length(a)
    println(a[i])
end

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


### Integers as Type Parameters

We saw with `NTuple` an integer `N` being used as a type parameter. We discuss about a Point type which can have N-axes. Then we define Point{2} and Point{3} as special cases for 2 and 3 dimentsions. 

In [16]:
struct Point{N}
    data::NTuple{N, Float32}
    Point(d...)=new{length(d)}(d)
end
const Point2D=Point{2}
const Point3D=Point{3}

function dist(p1::Point2D, p2::Point2D)
    dx, dy = (p1.data[1] - p2.data[1], p1.data[2] - p2.data[2])
    return sqrt(dx*dx+dy*dy)
end
function dist(p1::Point3D, p2::Point3D)
    dx, dy, dz = (p1.data[1] - p2.data[1], 
                  p1.data[2] - p2.data[2], 
                  p1.data[3] - p2.data[3])
    return sqrt(dx*dx+dy*dy+dz*dz)
end

dist (generic function with 2 methods)

In [17]:
dist(Point(1, 2), Point(3, 4))

2.828427f0

In [18]:
dist(Point(1, 2, 3), Point(3, 4, 5))

3.4641016f0

In [19]:
function dist(p1::Point{N}, p2::Point{N}) where N
    sumval = 0f0
    for i=1:N
        d = p1.data[i] - p2.data[i]
        sumval += d*d
    end
    return sqrt(sumval)
end

dist (generic function with 3 methods)

In [20]:
dist(Point(1, 2), Point(3, 4))

2.828427f0

In [21]:
dist(Point(1, 2, 3), Point(3, 4, 5))

3.4641016f0

In [22]:
function dist(p1::Point, p2::Point)
    N = length(p1.data)
    sumval = 0f0
    for i=1:N
        d = p1.data[i] - p2.data[i]
        sumval += d*d
    end
    return sqrt(sumval)
end

dist (generic function with 4 methods)

In [23]:
dist(Point(1, 2), Point(3, 4))

2.828427f0

In [24]:
dist(Point(1f0, 2f0, 3f0), Point(1, 2))


LoadError: BoundsError: attempt to access Tuple{Float32, Float32} at index [3]

In [25]:
function dist(p1::Point{N}, p2::Point{N}) where N
    sumval = 0f0
    for i=1:N
        d = p1.data[i] - p2.data[i]
        sumval += d*d
    end
    return sqrt(sumval)
end

function dist(p1::Point{N1}, p2::Point{N2}) where {N1, N2}
    N1 > N2 && return dist(p2, p1)
    tp = Point(p1.data..., ntuple(i->0f0, N2-N1)...)
    return dist(tp, p2)
end

dist (generic function with 4 methods)

In [26]:
dist(Point(1f0, 2f0, 3f0), Point(1, 2))

3.0f0

### Value Parameters

Dispatch based on an integer value. 

In [27]:
struct MyVal{N}
    MyVal(N)=new{N}()
end
f(::MyVal{N}) where N = N
function f(::MyVal{1})
    println("Called from 1")
end

f (generic function with 2 methods)

In [28]:
f(MyVal(2))

2

In [29]:
f(MyVal(1))

Called from 1


#### Singleton

In [30]:
MyVal(1) === MyVal(1)

true

In [31]:
MyVal(1) === MyVal(2)

false

In [32]:
MyVal(:a)

MyVal{:a}()

## 5.3 Ranges

Sequence of numbers maintaining a steady pattern. 

### UnitRange
Range of consecutive integers. 

In [33]:
a=1:5
typeof(a)

UnitRange{Int64}

In [34]:
for i=a
    println(i)
end

1
2
3
4
5


### StepRange

Ranges where integers are not consecutive but spaced by a step. 

In [35]:
b=1:2:5
typeof(b)

StepRange{Int64, Int64}

In [36]:
for i=b
    println(i)
end

1
3
5


### Decreasing Ranges

Ranges that are decreasing in value with a negative step. 

In [37]:
c=5:-1:1
typeof(c)

StepRange{Int64, Int64}

In [38]:
for i=c
    println(i)
end


5
4
3
2
1


In [39]:
d = 1:2.1:6.0

1.0:2.1:5.2

In [40]:
typeof(d)

StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}

## 5.4 Array
Mutable collection with a well defined memory layout.

In [41]:
v = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [42]:
m = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [43]:
m1 = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [44]:
m2 = [1 2; 3 4; 5 6]

3×2 Matrix{Int64}:
 1  2
 3  4
 5  6

### Memory Layout and Indexing

In [45]:
m1[1, 2]

2

In [46]:
m1[2, 2]

5

In [47]:
m2[1, 2]

2

In [48]:
m2[2, 2]

4

#### Effects of Paging

### Some Useful Functions

#### Constructors

In [49]:
Array{Int}(undef, 1, 2)

1×2 Matrix{Int64}:
 285212672  294777840

In [50]:
Array{Int}(undef, 2)

2-element Vector{Int64}:
         1
 292913488

In [51]:
Array{Int, 2}(undef, (2, 3))

2×3 Matrix{Int64}:
 0  1800763648           4
 1          10  1800763649

In [52]:
Array{Float32}(undef, (2, 3))

2×3 Matrix{Float32}:
 2.8844f-28  2.58078f26  2.58078f26
 0.0         0.0         0.0

In [53]:
struct A
    i::Int
    f::Float64
end
a = A(1, 1); isbits(a)

true

In [54]:
aarr = Array{A}(undef, (2, 2))

2×2 Matrix{A}:
 A(306343088, 1.41815e-315)  A(287035872, 1.41815e-315)
 A(287035552, 1.41815e-315)  A(292545552, 1.41815e-315)

In [55]:
struct T
    a::A
    b
end
b = T(A(1, 1), 1); isbits(b)

false

In [56]:
barr = Array{T}(undef, (2, 2))

2×2 Matrix{T}:
 #undef  #undef
 #undef  #undef

In [57]:
barr[1,1] = barr[2,1] = barr[1,2] = barr[2,2] = b

T(A(1, 1.0), 1)

In [58]:
barr

2×2 Matrix{T}:
 T(A(1, 1.0), 1)  T(A(1, 1.0), 1)
 T(A(1, 1.0), 1)  T(A(1, 1.0), 1)

In [59]:
Vector{Int}(undef, 3)

3-element Vector{Int64}:
 5
 4
 3

In [60]:
Matrix{Int}(undef, 3, 3)

3×3 Matrix{Int64}:
 262242640  262243040  254116912
 254115856  262243120  262243280
 262242960  262243200  262242880

#### zeros and ones

In [61]:
zeros(Float32, (2, 3))

2×3 Matrix{Float32}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [62]:
ones(Float32, (2, 3))

2×3 Matrix{Float32}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [63]:
ones(UInt8, (2, 3))

2×3 Matrix{UInt8}:
 0x01  0x01  0x01
 0x01  0x01  0x01

#### trues and falses

Return `BitArray`, which are optimal `Array{Bool}` like types but take 1/8-th of the space. 

In [64]:
zb = zeros(Bool, (8, 8))

8×8 Matrix{Bool}:
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0

In [65]:
sizeof(zb)

64

In [66]:
z = falses(8, 8)

8×8 BitMatrix:
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0

In [67]:
sizeof(z)

8

#### fill and similar

In [68]:
a = fill(5.0, (2, 2))

2×2 Matrix{Float64}:
 5.0  5.0
 5.0  5.0

In [69]:
a = fill(5, (2, 2))

2×2 Matrix{Int64}:
 5  5
 5  5

In [70]:
b = similar(a, Int)

2×2 Matrix{Int64}:
  298460432  1803755680
 1803755680           0

#### collect

Enumerates over a collection and return an array with all elements populated. 

In [71]:
collect(1:3)

3-element Vector{Int64}:
 1
 2
 3

In [72]:
collect(Float64, 1:2:3)

2-element Vector{Float64}:
 1.0
 3.0

#### reshape

Reshape an array to various sizes while keeping the row major ordering intact.

In [73]:
a = collect(1:16)

16-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16

In [74]:
b = reshape(a, (4, 4))

4×4 Matrix{Int64}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

In [75]:
c = reshape(b, (2, 8))

2×8 Matrix{Int64}:
 1  3  5  7   9  11  13  15
 2  4  6  8  10  12  14  16

In [76]:
d = reshape(c, (8, 2))

8×2 Matrix{Int64}:
 1   9
 2  10
 3  11
 4  12
 5  13
 6  14
 7  15
 8  16

#### hcat, vcat and hvcat

Concatenation of arrays vertically, horizontally or both when the dimensions are aligned properly. 

In [77]:
vcat([1 2; 3 4], [5 6; 7 8], [9 10; 11 12])

6×2 Matrix{Int64}:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [78]:
hcat([1 2; 3 4], [5 6; 7 8], [9 10; 11 12])

2×6 Matrix{Int64}:
 1  2  5  6   9  10
 3  4  7  8  11  12

In [79]:
hvcat((2, 2, 2), [1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12])

6×2 Matrix{Int64}:
  1   3
  2   4
  5   7
  6   8
  9  11
 10  12

In [80]:
hvcat(6, [1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12])

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

## 5.5 Associative Collection

A collection where a key and value are kept associated. The keys are used for accessing the elements of the collection. 

### Dict

A hash based dictionary.

In [81]:
d = Dict("a"=>1, "c"=>2, "b"=>3)

Dict{String, Int64} with 3 entries:
  "c" => 2
  "b" => 3
  "a" => 1

In [82]:
d["b"]

3

In [83]:
d["a"] = 5

5

In [84]:
println(d)

Dict("c" => 2, "b" => 3, "a" => 5)


In [85]:
d = Dict("a"=>1, "c"=>2, "b"=>3, "a"=>4)

Dict{String, Int64} with 3 entries:
  "c" => 2
  "b" => 3
  "a" => 4

#### get Methods

In [86]:
get(d, "a", 3)

4

In [87]:
get(d, "e", 0)

0

In [88]:
getindex(d, "e")

LoadError: KeyError: key "e" not found

In [89]:
d["e"]

LoadError: KeyError: key "e" not found

In [90]:
get!(d, "a", 0)

4

In [91]:
get!(d, "e", 0)

0

In [92]:
d

Dict{String, Int64} with 4 entries:
  "c" => 2
  "e" => 0
  "b" => 3
  "a" => 4

#### setindex! Method

In [93]:
d["e"] = 10

10

In [94]:
setindex!(d, 11, "e")

Dict{String, Int64} with 4 entries:
  "c" => 2
  "e" => 11
  "b" => 3
  "a" => 4

### Set

Collection of belonging. Unique elements only. 

In [95]:
s = Set([2 3 4 5 1 2 3])

Set{Int64} with 5 elements:
  5
  4
  2
  3
  1

In [96]:
6 in s

false

In [97]:
5 in s

true

In [98]:
t = Set([4 5 7 8 9])

Set{Int64} with 5 elements:
  5
  4
  7
  9
  8

#### Union and Intersection

In [99]:
union(s, t)

Set{Int64} with 8 elements:
  5
  4
  7
  2
  9
  8
  3
  1

In [100]:
intersect(s, t)

Set{Int64} with 2 elements:
  5
  4

In [101]:
union!(s, t)

Set{Int64} with 8 elements:
  5
  4
  7
  2
  9
  8
  3
  1

In [102]:
s

Set{Int64} with 8 elements:
  5
  4
  7
  2
  9
  8
  3
  1

## 5.6 Iteration 

All collections are enabled for iteration. This requires the collections to implement certain interfaces / functions. 

### for loop

In [103]:
for i=5:-2:1
    println(i)
end

5
3
1


In [104]:
b = [1.0 2 3; 4 5 6; 7 8 9]
for i=b
    println(i)
end

1.0
4.0
7.0
2.0
5.0
8.0
3.0
6.0
9.0


In [105]:
for p in d
    println(p)
end

"c" => 2
"e" => 11
"b" => 3
"a" => 4


In [106]:
for (k, v) in d
    println("Key:", k," Value:", v)
end

Key:c Value:2
Key:e Value:11
Key:b Value:3
Key:a Value:4


### function...do

A very neat way to code for function that applies to every element of the collection. `map` is a useful method that is in-built to address such needs. 

In [107]:
function collect_square(v)
    a = similar(v)
    for i=1:length(v)
        a[i] = v[i]*v[i]
    end
    return a
end
collect_square(1:4)

4-element Vector{Int64}:
  1
  4
  9
 16

In [108]:
function collect_function(f::Function, v)
    a = similar(v)
    for i=1:length(v)
        a[i] = f(v[i])
    end
    return a
end
collect_function(x->x^3, 1:4)

4-element Vector{Int64}:
  1
  8
 27
 64

In [109]:
collect_function(1:4) do x
    return x^3
end

4-element Vector{Int64}:
  1
  8
 27
 64

In [110]:
map(1:4) do x
    return x^3
end

4-element Vector{Int64}:
  1
  8
 27
 64

## 5.7 Iteration Framework

Custom collection authors must implement the iteration framework. 

In [111]:
v = collect(3:2:10)

4-element Vector{Int64}:
 3
 5
 7
 9

In [112]:
for i=v
    println(i)
end

3
5
7
9


In [113]:
next = iterate(v)

(3, 2)

In [114]:
while next !== nothing
    value, state = next
    println(value)
    next = iterate(v, state)
end


3
5
7
9


### iterate Methods

### Optional Methods

In [115]:
Base.IteratorSize(Vector{Int})

Base.HasShape{1}()

In [116]:
Base.IteratorEltype(Vector{Int})

Base.HasEltype()

In [117]:
eltype(Vector{Int})

Int64

### Example

In [118]:
struct Squares
    value::Int
end
Base.iterate(s::Squares) = s.value <= 0 ? nothing : (1, 2)

Base.iterate(s::Squares, state) = s.value < state ? nothing :      
    (state*state, state+1)

In [119]:
for i=Squares(3)
    println(i)
end

1
4
9


In [120]:
collect(Squares(3))

LoadError: MethodError: no method matching length(::Squares)
Closest candidates are:
  length(::Union{Base.KeySet, Base.ValueIterator}) at abstractdict.jl:58
  length(::Union{LinearAlgebra.Adjoint{T, S}, LinearAlgebra.Transpose{T, S}} where {T, S}) at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\adjtrans.jl:195
  length(::Union{ZMQ._Message, Base.RefValue{ZMQ._Message}}) at C:\Users\shalo\.julia\packages\ZMQ\R3wSD\src\_message.jl:31
  ...

In [121]:
Base.length(s::Squares)=s.value

In [122]:
collect(Squares(3))

3-element Vector{Any}:
 1
 4
 9

In [123]:
Base.eltype(::Type{Squares})=Int

In [124]:
eltype(Squares)

Int64

In [125]:
collect(Squares(3))

3-element Vector{Int64}:
 1
 4
 9

## 5.8 Generators and Comprehensions

Comprehensions are a simple notation to create arrays. Generators provide the iterator interface and elements get computed only when iterated upon. 

In [126]:
[i*i for i=1:3]

3-element Vector{Int64}:
 1
 4
 9

In [127]:
[i*j for i=1:3, j=1:3]

3×3 Matrix{Int64}:
 1  2  3
 2  4  6
 3  6  9

In [128]:
[i*j for i=1:3 for j=i:3]

6-element Vector{Int64}:
 1
 2
 3
 4
 6
 9

In [129]:
gen=(i*j for i=1:3 for j=i:3)

Base.Iterators.Flatten{Base.Generator{UnitRange{Int64}, var"#22#23"}}(Base.Generator{UnitRange{Int64}, var"#22#23"}(var"#22#23"(), 1:3))

In [130]:
for v=gen
    println(v)
end

1
2
3
4
6
9
